
my_text_file = open('Task 5.2_SAV.txt', 'r')
content = my_text_file.read()
print(f'Содержимое файла: \n {content}')
my_text_file = open('Task 5.2_SAV.txt', 'r')
content = my_text_file.readlines()
print(f'Количество строк в файле: {len(content)}')
my_text_file = open('Task 5.2_SAV.txt', 'r')
content = my_text_file.readlines()
for i in range(len(content)):
    print(f'Количество символов {i + 1}-ой строки: {len(content[i])}')
my_text_file = open('Task 5.2_SAV.txt', 'r')
content = my_text_file.read()
content = content.split()
print(f'Общее количество слов: {len(content)}')
my_text_file.close()